### ISSUE TITLE
error highlight in scss file!

### ISSUE THREAD

**Issue by IndexXuan** [hail2u/vim-css3-syntax#34]
VIM 7.4.52 in ubuntu 14.04

maybe conflict with `scss-syntax.vim` plugin

the problem is if I use your  plugin, I have right css3 highlight,  while error highlight in nested scss syntax, parent's right '}' is always highlight for error.

```scss
.parent { 
　　width: 100px; 
　　height: 100px;
 
　　.child{
　　　　width: 10px; 
　　　　height: 10px;
　　} 
}　// highlight here...
```

If I don't use your plugin, I will not have right css3 highlight...

while 
```shell 
rm ~/.vim/bundle/vim-css3-syntax/after/syntax/scss.vim
```  
Both works.

Maybe the problem in my pc...

**Comment by hail2u** [comment]
Your example code uses full-width spaces for indentation. I’m very confused. Please paste the correct example and upload a screenshot of error!

**Comment by IndexXuan** [comment]
sorry for my indentation fault...

you can see like this.
![scss-nested-highlight-error-201601211540](https://cloud.githubusercontent.com/assets/6322673/12474383/c50fbee2-c055-11e5-8156-e337c2fdaac1.png)

after rename the ` /.vim/bundle/vim-css3-syntax/after/syntax/scss.vim` as `scss-back.vim`

it becomes well enough~

![screenshot from 2016-01-21 15 46 08](https://cloud.githubusercontent.com/assets/6322673/12474443/45c23470-c056-11e5-81fc-dab19b1f34b9.png)

**Comment by hail2u** [comment]
It seems to break child selector (`.child`) highlighting not only `}`. So, it is a bug of a nesting highlight. 

`vim-css3-syntax` plugin doesn’t have these type of highlight. I think this is a problem of `scss-syntax.vim`. I will look it.Thanks for reporting!

**Comment by IndexXuan** [comment]
Thanks for your attention~ 3q very much !

**Comment by hail2u** [comment]
Good to know. I cannot reproduce your problem. If some similar problem happen, open this issue again.
