### ISSUE TITLE
Missing `pointer-events`

### ISSUE THREAD

**Issue by othree** [hail2u/vim-css3-syntax#37]
`pointer-events` is not highlight.
I think this is missing one.

<https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events>

**Comment by hail2u** [comment]
It’s supported by JulesWang/css.vim#54 (this is the Vim’ v7.x default CSS syntax plugin). I don’t want to add non-standard properties to this plugin because these are hard to maintain.

**Comment by othree** [comment]
Thanks, I think Jules Wang still not sent back to upstream.

BTW, this property is in SVG standard.
Not really a non-stadard property.

**Comment by hail2u** [comment]
- We can replace built-in CSS syntax plugin easily
- It is certainly a standard in SVG, but not in CSS
- It is a vendor extension like `ime-mode` property

I don’t think it is worth supporting this property in my plugin.
