### ISSUE TITLE
You may want to add some of WebKit-prefixed things in the Compat spec

### ISSUE THREAD

**Issue by upsuper** [hail2u/vim-css3-syntax#38]
There are several WebKit-prefixed things standardized in [the Compatibility Standard](https://compat.spec.whatwg.org/). You may want to add them to the syntax file.

**Comment by hail2u** [comment]
I don’t want to.

**Comment by upsuper** [comment]
Their being standardized means they would not be
* added frequently
* changed unexpectedly
* removed silently

What's the reason not to add them, then?

**Comment by upsuper** [comment]
There was actually some [discussion in CSSWG proposing adding those WebKit-prefixed things into CSS specs directly](https://lists.w3.org/Archives/Public/www-style/2015Dec/0132.html). Apple actively opposes that, though.

**Comment by hail2u** [comment]
They will be renamed if some CSS spec adds their compatible things. And they will be removed without any notice (WebKit dev docs didn’t mention removal of minor features in the past).

If CSSWG adds this spec to [the list of related specifications][1], I will certainly supports!

[1]: https://www.w3.org/Style/CSS/current-work#other

**Comment by upsuper** [comment]
They will not be renamed, because doing so would break the web. And that's the reason behind developing the Compatibility Standard.

**Comment by upsuper** [comment]
FWIW, you may want to look at [CSSWG's draft repo](https://drafts.csswg.org/) rather than the list on W3C.

**Comment by hail2u** [comment]
> They will not be renamed
I don’t think this is guaranteed by WebKit (or Apple). Is there any official announcement?

I don’t support editor’s drafts because they are updated frequently. I have no time to track them.

**Comment by upsuper** [comment]
> I don’t think this is guaranteed by WebKit (or Apple). Is there any official announcement?

They just don't dare to... The things listed in the Compatibility Standard are also implemented or being implemented by other browsers. Edge has supported many of them, and we (Gecko) has implemented many of them as well, although it is not turned on by default yet. And our new browser engine Servo will need to implement those stuffs as well.

**Comment by hail2u** [comment]
I want to only support things stable and guaranteed.

I will reconsider it if this spec is listed on current work or mentioned on core CSS spec such as snapshot spec.
