### ISSUE TITLE
Extremely slow on startup

### ISSUE THREAD

**Issue by boompig** [hail2u/vim-css3-syntax#45]
I noticed my vim startup time was very slow when loading a file. I profiled with

`vim --startuptime vim.log`

Here I noticed vim actually started very quickly, much quicker than when actually loading a buffer. What's going on? I profiled again with the buffer loading:

```
vim --startuptime vim-readme.log README.md
vim --startuptime vim-nobuffer.log
```

I noticed that my startup time was ~300ms for the case without a buffer and ~2500ms with the README.md file (the file has 1 line).

I view the log files side by side:

`diff --side-by-side vim-readme.log vim-nobuffer.log --width 220 | less`

In the vim-readme case the screen is cleared (line `clearing screen`) at around 300ms, after which there is a huge amount of plugins sourced. Since many plugins have multiple files I wanted to group by file, after the initial 300ms.

I wrote a short Python script [Github gist here](https://gist.github.com/boompig/c085b52b34901d9a1793a6005df4128a) which counted the number of times the file was sourced and how long the total time was and sorted descending by time. The top 10 results:

```
/Users/daniel_kats/.vim/plugged/vim-css3-syntax/after/syntax/html.vim -> 1633.521 ms (2 occurrences)
/Users/daniel_kats/.vim/colors/github.vim -> 93.303 ms (3 occurrences)
/usr/local/share/vim/vim74/syntax/html.vim -> 88.008 ms (2 occurrences)
/usr/local/share/vim/vim74/ftplugin/markdown.vim -> 75.706 ms (2 occurrences)
/Users/daniel_kats/.vim/colors/molokai.vim -> 40.774 ms (1 occurrences)
/usr/local/share/vim/vim74/syntax/css.vim -> 26.084 ms (2 occurrences)
/usr/local/share/vim/vim74/syntax/markdown.vim -> 25.842 ms (2 occurrences)
/usr/local/share/vim/vim74/syntax/vb.vim -> 7.192 ms (2 occurrences)
/Users/daniel_kats/.vim/plugged/vim-css3-syntax/after/syntax/css/css-counter-styles-3.vim -> 6.836 ms (2 occurrences)
/usr/local/share/vim/vim74/syntax/syncolor.vim -> 6.179 ms (11 occurrences)
```

A few interesting things here:

* why is the CSS3 plugin taking any time to source at all, given this is a README file?
* why is the CSS3 plugin taking 1633!!! ms to load?

Note that this doesn't even group by plugin, just by file. If I were to group by plugin, then css3-syntax plugin would take even more time.

What is the cause of this?

**Comment by boompig** [comment]
After disabling the `vim-css3-syntax` extension my startup time dropped from ~2.5 seconds to ~0.9 seconds.

**Comment by hail2u** [comment]
> why is the CSS3 plugin taking any time to source at all, given this is a README file?

`README.md`  seems a Markdown file. A Markdown file loads Markdown syntax file, Markdown syntax file calls HTML syntax file, and HTML syntax calls this plugin.

> why is the CSS3 plugin taking 1633!!! ms to load?

This plugin is not fast, but I don’t think it is a generic problem. This plugin costs only `187ms` on my machine.

```
1047.000  000.000: --- VIM STARTED ---
```

Also Vim starts in `1047ms`.

> What is the cause of this?

I don’t know.
