### ISSUE TITLE
Makes file very slow to open

### ISSUE THREAD

**Issue by Jab2870** [hail2u/vim-css3-syntax#49]
I have a file that is 744 lines long.  With theis plugin enabled it takes over 10 seconds to open.  With the plugin disabled it is more or less instant

**Comment by hail2u** [comment]
It seems to be a problem of your environment or your CSS code itself. My 609 lines of CSS and Amazon’s 1500 lines of CSS can be opened under 1 second. Please reopen with reproducable CSS file.
