### ISSUE TITLE
make it support for qss

### ISSUE THREAD

**Issue by xyz1001** [hail2u/vim-css3-syntax#52]

**Comment by xyz1001** [comment]
I'm a Qt developer and I have to write .qss file, which has the same sytax with CSS. Counld you tell me how to make this plugin work with .qss file? any help would be appreciated.

**Comment by leycec** [comment]
@xyz1001 Doing so should be trivially feasible. While untested, inserting the following lines towards the start of your `~/.vimrc` file *should* theoretically work:

```
augroup my_filetype_detect
    autocmd!

    " Associate filetype ".qss" with the CSS mode.
    autocmd BufNewFile,BufRead *.qss setfiletype css
augroup END
```

That said, note that Qt StyleSheet (QSS) syntax only superficially resembles Cascading Style Sheet (CSS). There are substantial differences, both above and below the hood. In other words, attempting to force Vim to parse the former as if it were the latter may horribly blow up your entire life. 💣 

Ideally, `vim-css3-syntax` would add explicit support for QSS at some point. Or is it that unthinkable heresy, @hail2u?

**Comment by hail2u** [comment]
I don’t want to support CSS-like something anymore. You can write your own plugin like [VIM-LESS](https://github.com/groenewege/vim-less/blob/6e818d5614d5fc18d95a48c92b89e6db39f9e3d6/syntax/less.vim#L8).

**Comment by mxaddict** [comment]
@leycec  thanks for that idea :dagger:
