### ISSUE TITLE
Incorrect highlighting for: space-{around|evenly|between} and ease-in-out

### ISSUE THREAD

**Issue by iFallUpHill** [hail2u/vim-css3-syntax#58]
<img width="283" alt="screen shot 2018-02-05 at 3 29 13 pm" src="https://user-images.githubusercontent.com/8867997/35792725-76a6478c-0a89-11e8-9d66-845bddff9e4a.png">

Using the latest vim-css3-syntax, happening in both Vim and NeoVim for *.css files with any color scheme (Dracula in the example screenshot).  

```
> vim --version
8.0 with patches 1-1427

> nvim -v
NVIM v0.2.2
```

**Comment by hail2u** [comment]
![20180205164225](https://user-images.githubusercontent.com/68940/35793173-db6ef13c-0a93-11e8-8ed5-23c9ed8ef9c9.png)

Some people told me about these type of issue. But I cannot reproduce on Vim and gVim.

**Comment by iFallUpHill** [comment]
Maybe I'll take a look on another computer with vim then. To be fair, I've always used nvim so I might have not made sure I configured this correctly with vim. 

If it helps I'm using a Mac and this happens in both iTerm and Terminal.

**Comment by iFallUpHill** [comment]
Update: Tried on another Mac with Vim 8.0.1427 (via Homebrew) and see the same thing.

Here's what it looks like on my Mac (Vim 8.0.1427 on the left, NeoVim 0.2.2 on the right).
<img width="694" alt="screen shot 2018-02-05 at 4 15 40 pm" src="https://user-images.githubusercontent.com/8867997/35794238-ef93260a-0a8f-11e8-8dc5-f66bb09f9e1e.png">

**Comment by iFallUpHill** [comment]
Well, after some fiddling around with the source files, I decided to try `setlocal iskeyword+=-` again and it worked this time. Now sure why it didn't work the first time, but at least it works now. Sorry about that! 

Closing this now.
