### ISSUE TITLE
Submit these improvements as PRs to the official Vim CSS syntax file

### ISSUE THREAD

**Issue by jsit** [hail2u/vim-css3-syntax#65]
Vim natively ships with this CSS syntax file:

https://github.com/JulesWang/css.vim

It would be more helpful if these improvements were submitted as PRs to that repo.

**Comment by hail2u** [comment]
Some (50%~) of properties/values defined in this syntax file are: 

- experimental
- not stable
- not implemented

So, it must not be merged into official syntax file, I think.
