### ISSUE TITLE
Inline styles syntax highlight

### ISSUE THREAD

**Issue by timsofteng** [hail2u/vim-css3-syntax#68]
Hey. What can I do to enable css syntax highlight of inline stylse?

![image](https://user-images.githubusercontent.com/51912173/92370118-86adff00-f102-11ea-8a44-b0a886cf9b11.png)

**Comment by hail2u** [comment]
It is not a job of this CSS syntax plugin. Ask a maintainer of Vim’s *HTML* syntax.
