### ISSUE TITLE
master -> main

### ISSUE THREAD

**Issue by gilgameshskytrooper** [hail2u/vim-css3-syntax#69]
I use vim-css3-syntax through SpaceVim (Dein plugin installer).

Since last night, when I run `:SPU`, I noticed I got the error `x vim-css3-syntax: Updating failed,  The plugin dir is dirty`.

![img1](https://drive.voiceit.io/files/vim-css3-syntax-1.png)

When I go to the cloned repo itself (`~/.cache/vimfiles/repos/github.com/hail2u/vim-css3-syntax`), and run `git log origin/master..HEAD`, I get the following logs:

```
commit 5a004b69ad3ee4435553004288b2e44f0941e549 (HEAD -> master)
Author: Kyo Nagashima <hail2u@gmail.com>
Date:   Sat Nov 21 08:41:21 2020 +0900

    Update text-3.vim

    https://www.w3.org/TR/2020/WD-css-text-3-20201119/

commit 750667a31252ded5a989955afca864968ef0fe52
Author: Kyo Nagashima <hail2u@gmail.com>
Date:   Thu Nov 19 16:24:04 2020 +0900

    Update lists-3.vim

    https://www.w3.org/TR/2020/WD-css-lists-3-20201117/

commit ab5722664a12667077083e80aabbc014ad771e10
Author: Kyo Nagashima <hail2u@gmail.com>
Date:   Thu Nov 19 16:21:47 2020 +0900

    Update fonts-4.vim

    https://www.w3.org/TR/2020/WD-css-fonts-4-20201117/
```

![img2](https://drive.voiceit.io/files/vim-css3-syntax-2.png)

These show up as "changes that have not been pushed" in my repo.

Checking your remote repository, it seems you changed the `master` branch to be `main` and I believe this might be the issue.

いずれみんな `master branch` から `main branch` に切り替える時が来ると思いますが、今現在`git pull` に頼る Dein などのソフトはまだ `master branch` と `main branch`を両立できない状態であると僕は考えてます。

そこで「両立サポート」が普及するまでは、`master branch` と`main branch`を両方とも更新続けられればありがたいです。

よろしくお願いします。

**Comment by hail2u** [comment]
Thanks, I reverted master branch, and will update both branches for a while.
